# Copyright 2019
#
# Workshop Ninja Python

runtime: python
env: flex
# Gunicorn "Green Unicorn" es un Python Web Server.
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

beta_settings:

