runtime: python27
api_version: 1
threadsafe: true
# TODO: Indicar aquí el UID del usuario en minúscula
service: <uid>

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /bootstrap
  static_dir: bootstrap
  secure: always

- url: /.*
  script: main.app
  login: required
  secure: always
# [END handlers]

# [START libraries]
# webapp2: Marco de trabajo web ligero de Python
# jinja2: Lenguaje de plantilla moderno y de diseño amigable para Python
# werkzeug: Biblioteca de herramientas de WSGI
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: werkzeug
  version: latest
# [END libraries]



